function Hd = pass1_stop5v2
%PASS1_STOP5V2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 06-Dec-2015 23:10:18

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 800;  % Sampling Frequency

Fpass = 1;       % Passband Frequency
Fstop = 5;       % Stopband Frequency
Apass = 0.1;     % Passband Ripple (dB)
Astop = 80;      % Stopband Attenuation (dB)
match = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% Get the transfer function values.
[b, a] = tf(Hd);
g = prod(Hd.ScaleValues);				% Calculate gain factor

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);
a = Hd.Denominator; b = Hd.Numerator;	% Grab coefficients
z = roots(b); p = roots(a);				% Calculate poles/zeros
zp2biquad(z,p,g,'pass1_stop5v2.c');		% Dump filter coefs to file

% [EOF]
