%% ECE486 Lab 3 - Task 3/4
% This script is a secondary test of the zp2biquad() function written for Task 3. 
% The filter designed in Task 2 was split into 5 biquad sections using the
% coefficients generated by the zp2biquad() function.
%
% Authors: Jacob Allenwood, Travis Russell, Jeremiah Simonsen
% ECE 486 - Laboratory 3
% March 10, 2015

f = linspace(0,0.5,1001);
z = exp(1i*2*pi*f);
G_1 = 0.02247370*(1 - 1.998995*z.^(-1) + 1*z.^(-2))./ ...
    (1 - 1.9985678*z.^(-1) + 0.9985801*z.^(-2));
G_2 = 0.01228595*(1 - 1.99775928*z.^(-1) + 1*z.^(-2))./ ...
    (1 - 1.99785365*z.^(-1) + 0.99786011*z.^(-2));
G_3 = 0.002895762*(1 - 1.9819549*z.^(-1) + 1*z.^(-2))./ ...
    (1 - 1.9819548998*z.^(-1) + 0.997463175*z.^(-2));
G_4 = 0.0001253464*(1 - 1.99927548*z.^(-1) + 1*z.^(-2))./ ...
    (1 - 1.9994872767*z.^(-1) + 0.99950375427*z.^(-2));

plot(f,20*log10(abs(G_1.*G_2.*G_3.*G_4)))
% axis([0 0.5 -45 5])
grid on
xlabel('Normalize Frequency, cycles/sample')
ylabel('G(f) Filter Gain, dB')
title('Cascaded Biquads Response')