%% ECE486 Lab 3 - Task 3/4
% This script is a secondary test of the zp2biquad() function written for Task 3. 
% The filter designed in Task 2 was split into 5 biquad sections using the
% coefficients generated by the zp2biquad() function.
%
% Authors: Jacob Allenwood, Travis Russell, Jeremiah Simonsen
% ECE 486 - Laboratory 3
% March 10, 2015

f = linspace(0,0.5,1001);
z = exp(1i*2*pi*f);
G_1 = (1 - 1.8256*z.^(-1) + 1*z.^(-2))./(1 - 1.94551*z.^(-1) ...
    + 0.946985*z.^(-2));
G_2 = (1 - 1.9673*z.^(-1) + 1*z.^(-2))./(1 - 1.97569*z.^(-1) ... 
    + 0.979843*z.^(-2));

plot(f,20*log10(abs(0.00101447*G_1.*G_2)))
% axis([0 0.5 -45 5])
grid on
xlabel('Normalize Frequency, cycles/sample')
ylabel('G(f) Filter Gain, dB')
title('Cascaded Biquads Response')